# 一、ndarray
## nadarray的特性
## 多维性

In [5]:
import numpy as np
from numpy.ma.core import concatenate

In [6]:
arr = np.array(5)  # 创建0维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)  # 数组的维度 number of demensions

5
arr的维度： 0


In [5]:
arr = np.array([1, 2, 3])  # 创建1维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)  # 数组的维度 number of demensions

[1 2 3]
arr的维度： 1


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 创建2维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim)  # 数组的维度 number of demensions

[[1 2 3]
 [4 5 6]]
arr的维度： 2


# 同质性

In [ ]:
arr = np.array([1, 'hello'])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

In [ ]:
arr = np.array([1, 2.5])  # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

# 2.ndarray的属性

In [7]:
arr = np.array(1)  #
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)

1
数组的形状： ()


In [11]:
arr = np.array([1, 2.5, 3])  #
print(arr)
print('数组的形状：', arr.shape)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置：', arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
元素的个数： 3
元素的数据类型： float64
元素的转置： [1.  2.5 3. ]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 创建2维的ndarray数组
print(arr)
print('数组的形状：', arr.shape)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置：', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
元素的个数： 6
元素的数据类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


# 3.ndarray的创建

In [ ]:
# 基础的创建方法
list1 = [1, 2, 3]
arr = np.array(list1, dtype=float)
print(arr)
print(arr.ndim)


In [12]:
# copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是一个数组了;更改并不影响原数组
arr1[0] = 8
print(arr1)
print(arr)


[8.  2.5 3. ]
[1.  2.5 3. ]


In [15]:
# 预定义形状
# 全0 全1  未初始化 固定值
# 全0
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.ndim)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
2
int64


In [16]:
# 一维数组
arr = np.zeros((100,), dtype=int)
print(arr)
print(arr.ndim)
print(arr.dtype)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1
int64


In [18]:
# 全1
arr = np.ones((5, 7), dtype=int)
print(arr)
print(arr.ndim)
print(arr.dtype)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
2
int64


In [22]:
# 未初始化的
arr = np.empty((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
2
float64


In [24]:
# 固定值
arr = np.full((3, 4), 2025)
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:

arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.full_like(arr, 2026)
print(arr1)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2026. 2026. 2026.]
 [2026. 2026. 2026.]]


In [30]:
# 等差数列 2，4，6，8
arr = np.arange(1, 51, 1)  # start ,end,step(步长)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [33]:
# 等间隔数列
arr = np.linspace(0, 10, 5)
print(arr)  # [ 0.   2.5  5.   7.5 10. ]


[ 0.   2.5  5.   7.5 10. ]


array([  0,  25,  50,  75, 100])

In [35]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)  # [ 0.   2.5  5.   7.5 10. ]
arr = np.arange(0, 101, 25)
print(arr)


[  0  25  50  75 100]
[  0  25  50  75 100]


In [38]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=2)  # base默认是10为底
print(arr)


[ 1.  4. 16.]


In [39]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [41]:
# 对角矩阵：主对角线上的非零，其他的数字为0
arr = np.diag([1, 2, 3, 4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [43]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(3, 4)  # 随机数组的形状：3行4列
print(arr)

[[0.26517968 0.06713893 0.45533983 0.31854697]
 [0.8754348  0.13928543 0.08620945 0.44271693]
 [0.7887713  0.45674365 0.42540293 0.76570567]]


In [7]:
# 生成指定范围区间的随机浮点数(3到6之间)
arr = np.random.uniform(3, 6, (2, 3))  # 随机数组的形状：3行4列
print(arr)

[[4.15799763 5.55071794 4.54216681]
 [5.39889304 3.62376526 4.59169819]]


In [45]:
# 生成指定范围区间的随机整数(3到6之间)
arr = np.random.randint(3, 30, (2, 3))  # 随机数组的形状：3行4列
print(arr)

[[29 15 18]
 [15 16 13]]


In [3]:
# 生成随机数列（正态分布）（-3到3之间）
# 正态分布：两边小，中间大
arr = np.random.randn(2, 3)
print(arr)

[[-0.0791445  -0.15683299 -0.83462347]
 [-1.68013774 -1.21780793  0.40245613]]


In [57]:
# 设置随机种子,这里重复生成是一样的
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


# 4.ndarray的数据类型
 布尔类型 bool

 整数类型 int unit

 浮点数 float

 复数 complex



In [8]:
arr = np.array([1, 0, 2, 0], dtype=np.bool)  # 非零就是true
print(arr)

[ True False  True False]


# 5.索引与切片


In [12]:
# 一维数组的索引和切片
arr = np.random.randint(1, 100, 20)
print(arr)
print(arr[10])
print(arr[:])  #  获取全部的数据
print(arr[2:5])  #  start:end+1 左闭右开
print(arr[slice(2, 15, 3)])  # start ,end,step
print(arr[arr > 10])  #  布尔索引


[13  4 11 99 85 35 45  9  3 87 68  3 53 92 31 32 73 19  9 60]
68
[13  4 11 99 85 35 45  9  3 87 68  3 53 92 31 32 73 19  9 60]
[11 99 85]
[11 35  3  3 31]
[13 11 99 85 35 45 87 68 53 92 31 32 73 19 60]


In [18]:
# 二维数组的索引和切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[1, 3])  # 基础索引
print(arr[:, :])  #  获取全部的数据
print(arr[1, 1])  #  取第1行的数据,取第1列的数据
print('第3列的数据：', arr[:, 2])  #  取第3列的数据
# print(arr[slice(2,15,3)]) # start ,end,step
print(arr[arr > 50])  #  布尔索引
print(arr[2, :][arr[2] > 50])  #  获取行数据

[[14 36 93 58 82  4 76 44]
 [98 16 16 99 30 48 41 33]
 [80 83 86  2 75  6 61 94]
 [75 31 68 27 58 39 90 19]]
99
[[14 36 93 58 82  4 76 44]
 [98 16 16 99 30 48 41 33]
 [80 83 86  2 75  6 61 94]
 [75 31 68 27 58 39 90 19]]
16
第3列的数据： [93 16 86 68]
[93 58 82 76 98 99 80 83 86 75 61 94 75 68 58 90]
[80 83 86 75 61 94]


# 5.ndarray的运算

In [20]:
# 算数运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]
print(a * b)  # [ 4 10 18]
print(a / b)  # [0.25 0.4  0.5 ]



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [22]:
c = [1, 2, 3]
d = [4, 5, 6]
print(c + d)  # list是拼接的概念，并不是算数运算： [1, 2, 3, 4, 5, 6]
for i in range(len(c)):
    print(i)
    d[i] = d[i] + c[i]

print(d)

[1, 2, 3, 4, 5, 6]
0
1
2
[5, 7, 9]


In [26]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# 数组与标量之间的运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a + 3)
print(a - 3)
print(a * 3)
print(a / 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [29]:
# 广播机制:1.获取形状 2.是否可以广播
# 同一维度：相同、1
a = np.array([1, 2, 3])  # 一维数组 1*3
b = np.array([[1], [2], [3]])  # 二维数组 3*1
print('a数组是：', a)
print('b数组是：', b)
print('a+b:', a + b)
print('a-b:', a - b)



a数组是： [1 2 3]
b数组是： [[1]
 [2]
 [3]]
a+b: [[2 3 4]
 [3 4 5]
 [4 5 6]]
a-b: [[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]


In [31]:
# 矩阵的运算
'''

'''

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
'''
a：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 b：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
'''
print(a)
print(b)
print(a @ b)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# 2.3 numpy的常用函数
# 1.基本数学函数

In [32]:
# 算数平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))  # [1. 2. 3.]
arr = np.array([1, 25, 81])
print(np.sqrt(arr))  # [1. 5. 9.]


3.0
[1. 2. 3.]
[1. 5. 9.]


In [33]:
# 计算指数 e^x
print(np.exp(1))  # 默认是以e为底

2.718281828459045


In [34]:
# 计算自然对数 ln X (默认是为e)
print(np.log(2.71))

0.9969486348916096


In [36]:
# 计算正弦值、余弦值
print(np.sin(np.pi / 2))
print(np.cos(np.pi))

1.0
-1.0


In [37]:
# 计算绝对值
arr = np.array([1, -2, 9])
print(np.abs(arr))  # [1 2 9]


[1 2 9]


In [38]:
# 计算a的b次幂
print(np.power(arr, 2))  # [ 1  4 81]

[ 1  4 81]


In [39]:
# 四舍五入
print(np.round([3.4, 5.5, 5.6, 7, 9.1]))  #[3. 6. 6. 7. 9.]

[3. 6. 6. 7. 9.]


In [40]:
# 向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))


[ 2. 26. 82.]


In [41]:
# 检测缺失值NaN
print(np.isnan([1, 2, np.nan, 4]))  #[False False  True False]

[False False  True False]


# 2.统计函数
求和、求平均值、计算中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差


In [42]:
arr = np.random.randint(1, 20, 8)
print(arr)

[ 6 16  7  8  9 18  7 16]


In [43]:
# 求和
print(np.sum(arr))


87


In [44]:
# 计算平均值
print(np.mean(arr))

10.875


In [46]:
# 计算中位数
# 奇数：排序后中间的数值
# 偶数：中间两个数的平均值
print(np.median(arr))
print(np.median([1, 2, 4, 5]))  #3.0


8.5
3.0


In [50]:
# 计算标准差、方差
print(np.var([1, 2, 3]))
print(np.std([1, 2, 3]))
arr1 = np.array([1, 2, 1, 2, 2, 1, 1])
arr2 = np.array([1, 2, 1, 2, 1, 1, 1])
print(np.var(arr1))
print(np.var(arr2))
print(np.std(arr1))
print(np.std(arr2))

0.6666666666666666
0.816496580927726
0.24489795918367346
0.20408163265306126
0.4948716593053935
0.45175395145262565


In [51]:
# 计算最大值、最小值以及对应的索引
print(np.min(arr), np.argmin(arr))
print(np.max(arr), np.argmax(arr))

1
2


In [53]:
# 分位数
'''
      ----------------
分位数：1      2       3
中位数：1    2     3    4
'''
# 中位数
print(np.median([1, 2, 3]))
print(np.median([1, 2, 3, 4]))

np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
print(np.percentile(arr, 50))


2.0
2.5
[44 47 64 67]
55.5


In [54]:
# 累积的和、累积积
arr = np.array([1, 2, 3])
print(sum(arr))
print(np.cumsum(arr))  # [1 3 6]
print(np.cumprod(arr))  # [1 2 6]

6
[1 3 6]
[1 2 6]


## 比较函数
比较是否大于、小于、等于
逻辑与、或、非
检查数组中是否有一个True,是否所有的都为True,自定义条件

In [56]:
# 是否大于
print(np.greater([3, 4, 5, 6, 7], 5))  #[False False False  True  True]
# 是否小于
print(np.less([3, 4, 5, 6, 7], 4))  #[ True False False False False]
# 是否等于
print(np.equal([3, 4, 5, 6, 7], 4))  #[False  True False False False]
print(np.equal([3, 4, 5], [4, 4, 4]))  # [False True False]



[False False False  True  True]
[ True False False False False]
[False  True False False False]
[False  True False]


In [57]:
# 逻辑与、或、非
print(np.logical_and([1, 0], [1, 1]))  #[ True False]
print(np.logical_not([1, 0]))  # [False  True]
print(np.logical_or([3, 4, 5], [4, 4, 4]))  # [ True  True  True]


[ True False]
[False  True]
[ True  True  True]


In [58]:
# 检查元素是否至少有一个元素为True
print(np.any([1, 2, 3]))

True


In [59]:
# 自定义条件
# print(np.where(条件,符合条件,不符合条件))
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3, arr, 0))  # [0 0 0 4 5]
print(arr)  # [1 2 3 4 5]

[0 0 0 4 5]
[1 2 3 4 5]


In [61]:
np.random.seed(0)
scores = np.random.randint(0, 100, 20)
print(scores)
# 进行筛选
print(np.where(scores >= 60, '及格', '不及格'))


[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
['不及格' '不及格' '及格' '及格' '及格' '不及格' '及格' '不及格' '不及格' '及格' '及格' '及格' '及格'
 '不及格' '不及格' '及格' '不及格' '及格' '不及格' '及格']


In [62]:
print(np.where(scores < 60, '不及格', np.where(scores < 80, '良好', '优秀')))

['不及格' '不及格' '良好' '良好' '良好' '不及格' '优秀' '不及格' '不及格' '优秀' '良好' '优秀' '优秀'
 '不及格' '不及格' '良好' '不及格' '优秀' '不及格' '优秀']


In [64]:
# np.select(条件,返回的结果)
print(np.select([scores > 80, (scores >= 60) & (scores <= 80), scores < 60],
                ['优秀', '良好', '不及格'], default='未知'))

['不及格' '不及格' '良好' '良好' '良好' '不及格' '优秀' '不及格' '不及格' '优秀' '良好' '优秀' '优秀'
 '不及格' '不及格' '良好' '不及格' '优秀' '不及格' '优秀']


In [66]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
# arr.sort() # 会改变原来的数组
# print(arr)
print(np.sort(arr))
# 获取排序后的索引
print(np.argsort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [67]:
# 去重函数
print(np.unique(arr))


[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [69]:
# 数组的拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  #[5 7 9]
print(np.concatenate([arr1, arr2]))  #[1 2 3 4 5 6]

[5 7 9]
[1 2 3 4 5 6]


In [71]:
# 数组的分割
print(np.split(arr1, [2]))  # [array([1, 2]), array([3])]

[array([1, 2]), array([3])]


In [73]:
# 调整数据的形状
print(np.reshape([1, 2, 3, 4], (2, 2)))

[[1 2]
 [3 4]]


# 第2章NumPy科学计算综合练习


In [ ]:
'''
题目1:温度数据分析
某城市一周的最高气温（摄氏度）为[28,30,29,31,32,30,29]
-计算平均气温、最高气温、最低气温
-找出气温超过30摄氏度的天数
'''

In [81]:
import numpy as np

arrTem = np.array([28, 30, 29, 31, 32, 30, 29])
print(arrTem)
print(f'平均气温是：{np.mean(arrTem)}')
print(f'最高气温是：{np.max(arrTem)}')
print(f'最低气温是：{np.min(arrTem)}')
print('找出气温超过30摄氏度的天数')
print(len(arrTem[arrTem > 30]))
print(np.where(arrTem > 30, 1, 0))
print(np.cumsum(np.where(arrTem > 30, 1, 0))[-1])
print(np.count_nonzero(np.where(arrTem > 30, arrTem, 0)))

[28 30 29 31 32 30 29]
平均气温是：29.857142857142858
最高气温是：32
最低气温是：28
找出气温超过30摄氏度的天数
2
[0 0 0 1 1 0 0]
2
2


In [ ]:
'''
题目2:学生成绩统计
某班级 5 名学生的数学成绩为[85,90,78,92,88]
-计算成绩的平均分、中位数和标准差
-将成绩转换为百分制（满分是10）
'''

In [84]:
# import numpy as np
scores = np.array([85, 90, 78, 92, 88])
print(scores)
print('平均分：', np.mean(scores))
print('中位数：', np.median(scores))
print('方差：', np.var(scores))
print('成绩转换为十分')
print(np.divide(scores, 10))

[85 90 78 92 88]
平均分： 86.6
中位数： 88.0
方差： 23.84
成绩转换为十分
[8.5 9.  7.8 9.2 8.8]


In [ ]:
''''
题目3 矩阵运算
给定矩阵 A = [[1,2],[3,4]] 和B = [[5,6],[7,8]]
- 计算 A + B 和A * B
- 计算 A 和 B 的矩阵乘法（点积）

'''

In [89]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print(arr2)
# print(np.add(arr1, arr2))
print('A + B :',arr1 + arr2)
print('A * B :',arr1 *  arr2)
print('A @ B :',arr1 @  arr2)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
A + B : [[ 6  8]
 [10 12]]
A * B : [[ 5 12]
 [21 32]]
A @ B : [[19 22]
 [43 50]]


In [ ]:
'''
题目 4: 随机数据生成
生成一个(3,4)的随机整数数组，范围[0,10).
- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为-1；
'''

In [95]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3,4))
print(arr)
print('每列的最大值：',np.max(arr,axis=0)) # axis =0列，=1是行
print('每行的最小值：',np.min(arr,axis=1))
print(np.where(arr %2==1,-1,arr))
arr[arr % 2==1]=-1
arr[:,2]=-1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值： [7 9 7 6]
每行的最小值： [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [ ]:
'''
题目 5: 数组变形
创建一个 1到12的一维数组，并转换为（3，4）的二维数组
- 计算每行的和与每列的平均值
- 将数组展平为一维数组
'''

In [14]:
# 创建数组
import numpy as np
# arr = np.array(range(1,13))
arr = np.arange(1,13)
print('生成的一维数组：',arr)
# 转换为 二维数组
arr = np.reshape(arr,(3,4))
print('转换后的二维数组：',arr)
# 计算每行的和
print('每一行的和：',np.sum(arr,axis=1))
print('每一列的平均值：',np.mean(arr,axis=0))
# 将数组展平为一维数组
print('转换为一维数组',np.reshape(arr,(12)))

生成的一维数组： [ 1  2  3  4  5  6  7  8  9 10 11 12]
转换后的二维数组： [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每一行的和： [10 26 42]
每一列的平均值： [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
'''
题目 6: 布尔索引
生成一个（5，5）的随机数组，范围是[5,20).
- 找出数组中大于 10 的元素。
- 将所有大于 10 的元素替换为 0。
'''

In [20]:
# 生成随机数数组
# 固定重复
np.random.seed(0)
arr = np.random.randint(5, 20, (5,5))
print(f'生成的随机数数组是:\n{arr}')
# 找出数组中大于 10的元素
print(arr[arr >10 ])
# arr[arr >10 ]=0
print(np.where(arr >10 ,0 ,arr))


生成的随机数数组是:
[[17 10  5  8 16]
 [ 8 12 14  8 10]
 [ 7  9 12 11 13]
 [13 17 15  6 11]
 [12 12 19 13  6]]
[17 16 12 14 12 11 13 13 17 15 11 12 12 19 13]
[[ 0 10  5  8  0]
 [ 8  0  0  8 10]
 [ 7  9  0  0  0]
 [ 0  0  0  6  0]
 [ 0  0  0  0  6]]


In [25]:
'''
题目 7：统计函数应用
某公司 6 个月的销售额（万元）为[120,135,110,125,130,140]
- 计算出销售额的总和、均值、方差
- 找出销售额最高的月份和最低的月份
'''
money = np.array([120,135,110,125,130,140])
print(money)
print('总和：',np.sum(money))
print('均值：',np.mean(money))
print('方差：',np.var(money))
print(np.argmax(money) +1)
print(np.argmin(money)+1)


[120 135 110 125 130 140]
总和： 760
均值： 126.66666666666667
方差： 97.22222222222223
6
3


In [ ]:
'''
题目 8 ：数组拼接
给定 A = [1,2,3] 和 B =[4,5,6]
- 将 A 和 B 水平拼接成一个新数组
- 将 A 和 B 垂直拼接成一个新数组

'''

In [26]:
arr1 =[1,2,3]
arr2 =[4,5,6]
arr1 = np.array(arr1)
arr2 = np.array(arr2)
C =np.concatenate([arr1, arr2])
print(np.concatenate([arr1, arr2]))
print(C.reshape(C,(2,3)))


[1 2 3 4 5 6]


In [ ]:
'''
题目9 ：唯一值与排序
给定数组 [2,1,2,3,1,4,3]
- 找出数组中的唯一值并排序。
- 计算每个唯一值出现的次数。
'''

In [27]:
arr = np.array([2,1,2,3,1,4,3])
print(arr)
np.unique(arr)
u_arr,counts= np.unique(arr, return_counts=True)
print(u_arr)
print(counts)

[2 1 2 3 1 4 3]
[1 2 3 4]
[2 2 2 1]


In [32]:
'''
题目 10 ： 综合应用
某商店 5天的销售额（万元）和成本（万元）如下：
销售额： [20,25,22,30,28]
成本： [15,18,16,22,20]
-计算每天的利润
-计算利润的平均值和标准差
-找出利润最高的天数
'''
sales=np.array([20,25,22,30,28])
a=np.array([15,18,16,22,20])
money = sales -a
print('每天的利润',money)
print('利润的平均值：',np.mean(money))
print('利润的标准差：',np.std(money))
print('利润最高的天数：',len(money[money ==np.max(money)]))


每天的利润 [5 7 6 8 8]
利润的平均值： 6.8
利润的标准差： 1.16619037896906
利润最高的天数： 2
